### ISSUE TITLE
API to know when an AnimatedContainer is animating

### ISSUE THREAD

**Issue by Oreoz** [ember-animation/ember-animated#132]
_This is a question, not an issue._

Is there currently a public API in order to know when a `AnimatedContainer` is currently transitioning?

What I'm trying to accomplish here is for my `AnimatedContainer` to have certain classes during the animation and others when it's not animating. Perhaps there there is currently a way to accomplish this, but I'm not quite sure.

Pardon the extra issue, Discord is blocked at work so I couldn't ask over there.

**Comment by ef4** [comment]
Do you want to set the class in order to apply CSS styles? First I will assume yes and explain an alternate way to do that that gives ember-animated better control over the timing. Then I will go into the more general question of observing animations for reasons other than applying styles.

To fall within the tight timing requirements that would prevent things like flicker, you probably don't want to control styling from outside of motions. Meaning that for your particular use case, I think I would extend the default `Resize` motion that is already used by AnimatedContainer so it also adds the styles you want.

```js
// red-resize.js
import { Resize } from 'ember-animated/motions/resize';
class RedResize extends Resize {
  * animate() {
    // Whatever styles are changed here will get cleaned up
    // automatically when the animation is done.
    this.sprite.applyStyles({
      color: 'red'
    });
    // Run the default Resize animation to completion
    yield * super.animate();
  }
}

export default function redResize(sprite, opts) {
  return new RedResize(sprite, opts).run();
} 
```

```js
// your-component.js
import redResize from './red-resize';
export default class extends Component {
  motion=redResize
}
```

```hbs
// your-component.hbs
<AnimatedContainer @motion={{this.motion}} />
```

There is also a separate question of how to do things other than manipulating styles in response to animations starting and stopping. Particularly things like manipulating focus or scroll. For that, it's not enough to observe one animator component (like a particular `AnimatedContainer`), instead one usually needs to observe whether *any* of your ancestor and/or descendant components is animating. We currently have undocumented API on the `-ea-motion` service that can do this (`observeAnimations`, `observeDescendantAnimations`, `observeAncestorAnimations`, plus their matched `unobserve` methods). You should feel free to experiment with that. My plan for exposing it as public API it to do it as element modifiers, because the current API probably won't work with Glimmer components, and element modifiers would be more precise ("tell me when *this particular* DOM element's ancestors are animating", etc).

**Comment by Oreoz** [comment]
Thank you @ef4!

I only wanted to apply styles, so this covers my use case perfectly.

**Comment by andrewfan** [comment]
@ef4 @Oreoz hey, I see that addon has `motion` service where all animations are registered, also it has a property isAnimating` which might also help https://github.com/ember-animation/ember-animated/blob/master/addon/services/motion.js#L122

**Comment by basz** [comment]
Unfortunatly this results in an "Fatal error: Cannot read property 'onMotionStart' of null" for me (v0.8.1)

Trying to set "overflow: hidden" only while animating...

**Comment by basz** [comment]
For those who have the same issue as me... The `run()` call on the given code seems to be wrong.

```
export default function redResize(sprite, opts) {
  return new RedResize(sprite, opts).run();
} 
```
should be;

```
export default function redResize(sprite, opts) {
  return new RedResize(sprite, opts);
} 
```
