### ISSUE TITLE
z-index issue in hero demo

### ISSUE THREAD

**Issue by Cryrivers** [ember-animation/ember-animated#4]
as you can see, the animating element is behind other 'normal' elements.

![image](https://user-images.githubusercontent.com/1313238/30092581-4b24958c-92f2-11e7-99c2-f94d28c43a5c.png)

i think of a way to solve this is adding `ember-animated--animating` class to animating elements, then set z-index in CSS.

ef4 could you suggest a way to solve this? i can make a PR accordingly.

**Comment by ef4** [comment]
It's not as simple as that. In many cases, the other elements could be animating too. The "right" z-index for each element depends on the particular animation that the user has created.

In the case of the `hero` route in the demo app, the right behavior is probably to temporarily increase the z-index for sprites that you know you are moving. So somewhere in here:

https://github.com/ember-animation/ember-animated/blob/56e73003b15afb21ebac74ca475483f2396df8f9/tests/dummy/app/controllers/hero/index.js#L11-L13

you could do `sprite.applyStyles({ 'z-index': 1 })`.

The point of using a Sprite (instead of directly manipulating an Element) is that it can track a lot of state for us. In this case, it already knows what the element's final styles should be, and it will make sure the element ends up with them no matter what happens during the animation. So you don't need to unset the zIndex at the end of the animation.

**Comment by Cryrivers** [comment]
yes, using `applyStyles` is way better.
