### ISSUE TITLE
Embroider: ember-animated is trying to import from rsvp but that is not one of its explicit dependencies

### ISSUE THREAD

**Issue by wagenet** [ember-animation/ember-animated#451]
This warning does seem to be accurate. We should probably add rsvp as a peer dependency.

**Comment by ef4** [comment]
No, unfortunately `rsvp` is one of the things that ships inside `ember-source`. It would be bad to use any copy other than that one. Not only because of bloat, but because Ember [configures RSVP in a particular way](https://github.com/emberjs/ember.js/blob/3871ff92bce4f110689d1fd0ee8f625bd068b7ed/packages/%40ember/-internals/runtime/lib/ext/rsvp.ts#L6-L12), and that will only affect its own copy, not an extra copy.

Presumably you're hitting this exception only because by luck you have a real copy of rsvp that is resolvable in node_modules. A default ember app doesn't have that, which is why our tests don't pick up on this.

The real bug here is in embroider.
