### ISSUE TITLE
Pods-ify the AddonDocs site?

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#70]
Anyone opposed?

I find pods so much easier to work with...

**Comment by ef4** [comment]
I'm opposed. People keep overestimating how well-supported pods are. 

They don't have docs/guides to teach people how to use them.

And they're always the last to be able to benefit from build system improvements, because they introduce an entire new set of constraints that differ from the mainstream. Embroider, for example, has no pods support and isn't likely to get any any time soon unless somebody other than me with a pods app does the work.

**Comment by samselikoff** [comment]
😭

Some people keep saying pods don't have good support, but in an informal survey I did 50% of people use them, and I use them in all my apps and addons. I don't recall ever running into any issues. What kind of features do they lack support for?

**Comment by ef4** [comment]
I'm not saying they don't often work, I'm saying that there's literally no support policy for them. And there's no documentation.

That is two pretty serious strikes. People are free to use them, but they need to understand they're shouldering more responsibility when they do.

**Comment by ef4** [comment]
After followup discussion I give my blessing to using pods here. Opinions of people doing the work get more weight, and it's true that the downside risk is not large.
