### ISSUE TITLE
ember-animated-top-collapse sometimes added to first hero item

### ISSUE THREAD

**Issue by nickschot** [ember-animation/ember-animated#8]
When clicking through heroes which are not the first item, the '.ember-animated-top-collapse' class is sometimes added to only the first item, causing it to jump up during the animation. It seems to happen when transitioning in both directions (but not always!).

I'm not entirely familiar with the library yet, so I unfortunately haven't fully tracked it down.

First pointer: https://github.com/ember-animation/ember-animated/blob/a68fbb195fee72022fedfa27308826e27b333d4d/addon/sprite.js#L432

**Comment by ef4** [comment]
Thanks, I was aware there's a visual bug in that demo but hadn't had a chance to dig in further yet. 

If we are putting `ember-animated-top-collapse` onto the wrong things, the bug is probably in [margin-collapse.js](https://github.com/ember-animation/ember-animated/blob/16fdfbbbb696fb976286583f895db1004576e7ac/addon/margin-collapse.js)

**Comment by nickschot** [comment]
I can try to dig in in a couple of hours 👍

**Comment by ef4** [comment]
Also, to understand that code one should make sure they understand [margin collapse](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing).

In our case, we need to understand it because we are going to alter elements from being statically positioned to being absolutely positioned, and we don't want them to jump when we do that. So we need to know if they were already effected by margin collapse. And it's complicated because you may need to search arbitrarily deep through the DOM children to figure out which elements are effected.

**Comment by nickschot** [comment]
So here are my initial findings.

It seems that the first hero is detected during the `collapsedChildren` call from the `animated-bind` "index-route" which surrounds the hero-list. See: https://github.com/ember-animation/ember-animated/blob/16fdfbbbb696fb976286583f895db1004576e7ac/tests/dummy/app/templates/hero/index.hbs#L1 

Two ideas:
- A thing in play here which currently seems not to be taken into account: `display: flex`. There is no margin collapsing on a flex container (see first paragraph of: https://www.w3.org/TR/css-flexbox-1/#flex-containers ).
- There is a horizontal grid in the example (*if the above is fixed this does not apply to flex grids*). If it collapses any top margin, shouldn't it take the whole top row into account? Else we might still end up with jumping elements.

`collapsedChildren` is also called on each individual hero within the `animated-container` but here it is correctly detecting that it shouldn't collapse the margin for every hero and thus it isn't descending into their children.

**Comment by ef4** [comment]
Nice, I think this led me to the problem. Try master now with https://github.com/ember-animation/ember-animated/commit/96289c96eccf2571149866b35bc79cb7ae03fa6d

**Comment by nickschot** [comment]
That fixed it! 

On second thought, my second point isn't a problem. The only way you can currently make a wrapping grid is with `display: table` + `display: cell` (for which margins don't work anyway), with flexbox and maybe with floats. Margin collapsing doesn't seem to apply for any of them.
